Uploading the second css homework.
ok-technopolis-autumn-2019/Bakuta_Artem pull request #3
Opened 2019-11-15 09:16 UTC by Jhoysbou

2019-11-18 13:50 UTC, fromanywhere requested changes
Довольно странно, что нет package.json хотя бы с линтером

2019-11-18 13:50 UTC, fromanywhere commented on .idea/$PRODUCT_WORKSPACE_FILE$
> +<?xml version="1.0" encoding="UTF-8"?>
Учимся пользоваться гитигнором, в pr должны быть только значимые изменения

2019-11-18 13:50 UTC, fromanywhere commented on Style/action-bar.styl
> +.task-clear-completed
Стили  кнопки слетели мимо макета 
![image](https://user-images.githubusercontent.com/1042969/69057750-5ede9500-0a23-11ea-9f01-3124617eeffb.png)

2019-11-19 13:45 UTC, Jhoysbou commented on Style/action-bar.styl
> +.task-clear-completed
Странно, у меня кнопка отображается корректно. Можете подсказать, в чем дело?

<img width="1221" alt="Screen Shot 2019-11-19 at 16 30 09" src="https://user-images.githubusercontent.com/43999040/69151476-c3fdbd80-0aeb-11ea-87fb-1b9c4fea505e.png">

2019-11-20 20:04 UTC, fromanywhere commented on .gitignore
> +.stylelintrc
ну конфиг-то за что, чем же я линтить буду

2019-11-20 20:04 UTC, fromanywhere commented on Style/action-bar.styl
> +.task-clear-completed
Проблема была в указании стилей в style/style.css — он неправильно импортил reset, в котором определялись правила по кнопке и по шрифтам. Нужно было указать явно ссылку на style/style.styl, reset.css переименовать в reset.styl, пути в style дополнить префиксом ./, и тогда оно заработало

2019-11-20 20:11 UTC, fromanywhere commented on Style/action-bar.styl
> +.task-clear-completed
![image](https://user-images.githubusercontent.com/1042969/69274224-f7734180-0bea-11ea-833e-bbce19658214.png)
![image](https://user-images.githubusercontent.com/1042969/69274236-022dd680-0beb-11ea-8e2f-f5ac3fc550fe.png)

2019-11-21 12:13 UTC, Jhoysbou commented on Style/action-bar.styl
> +.task-clear-completed
Так я же не могу обращаться из html  напрямую к stylus. Я поменял все пути, но в html оставил, иначе ничего не работает.

2019-11-21 18:37 UTC, fromanywhere approved these changes

2019-11-21 20:56 UTC, merged